### ISSUE TITLE
To create a model for **textual similarity tasks** involving **JSON-structured data

### ISSUE THREAD

**Issue by BrunoRodolpho** [dwzhu-pku/PoSE#7]
My intention is to use the PoSE to pre/fine-train the LLM with diverse structured data like JSON and XML documents.
Unlike natural language text, structured data doesn't meaningful units sentences. Instead it consists of key-value pairs, nested objects, arrays, and etc. Besides that I am dealing with a very large documents like XML/JSONs with 100k+ tokens. 
Do you think I can use PoSE for that?

Regarding the script code: I am struggling to match the code with the paper.
Figure 6: Python Code used for calculating coverage probability of each relative position in Figure 5.
![PoSE](https://github.com/dwzhu-pku/PoSE/assets/5030787/67567ecd-82e1-40ec-b5f0-35096f15e4ae)

could you brief explain what these methods is doing? 
train_pose.py 
1) smart_tokenizer_and_embedding_resize
2) DataCollatorForSupervisedDataset
3) train_preprocess_function_randomized
4) train_preprocess_function_pose
5) Specific for train_preprocess_function_pose, is it correct the variable is assigned and never changed: lt1 = 0?

Thank you in advance.

**Comment by dwzhu-pku** [comment]
Hi @BrunoRodolpho, Thank you for your attention!

Firstly, the code snippets in Figure 6 are utilized to compute the coverage possibility of each relative position depicted in Figure 5. Therefore, the purpose of this code is to support the analysis conducted in Figure 5, Appendix B.

Our `train_pose.py` script is largely inherited from `train.py` sourced from [Llama-X](https://github.com/AetherCortex/Llama-X), which includes functions such as `smart_tokenizer_and_embedding_resize` and `DataCollatorForSupervisedDataset`. Hence, there is no need for additional focus on these two functions. `train_preprocess_function_randomized` is utilized to implement the baseline of RandPos. `train_preprocess_function_pose` is the crux of our method. During tokenization, this function will segment a piece of text into two chunks, and assign distinct positional encodings to each chunk. The positional encodings between the two chunks are discontinuous (we call it 'skipped'), with `lt0` representing the starting position of the first chunk. Since RoPE encodes relative positions, setting it to zero is OK (and we set it to zero intentionally).

I believe that PoSE is also applicable to unstructured data. However, I have not tested it on text similarity tasks yet, so I am also very curious about the outcomes. Looking forward to your response.
