### ISSUE TITLE
LM Evaluate

### ISSUE THREAD

**Issue by wutong4012** [dwzhu-pku/PoSE#8]
Thank you so much for your work and your open source code.
But some problems occurred when running lm_eval. I guess it is a version problem.
1. The current **lm-evaluation-harness** version does not have a **main** function, so I modified it to run in **lm-eval** mode;
2. The task **truthfulqa_mc** no longer exists, replaced by **truthfulqa_mc1** and **truthfulqa_mc2**, I guess it is **truthfulqa_mc1**;
3. The **hf-causal-experimental** model should be customized by the author, because the original **lm-evaluation-harness** does not have this type.
Please correct me if I have any problem.

**Comment by wutong4012** [comment]
@dwzhu-pku

**Comment by dwzhu-pku** [comment]
Hi @wutong4012! Thank you very much for your interest in our work! I'm sorry for forgetting to include the lm-evaluation-harness module in the repository, which would have facilitated an easier reproduction of this part. Due to a change in my development machine, I am currently unable to access the specific version of lm-evaluation-harness that was installed at the time. Therefore, I can only answer your questions based on my memory, and I hope this will be of some help to you. 

> 1. The current **lm-evaluation-harness** version does not have a **main** function, so I modified it to run in **lm-eval** mode; 

- It seems that the issue you've encountered is due to an update in **lm-evaluation-harness**. Your modification sounds very reasonable. 

> 2. The task **truthfulqa_mc** no longer exists, replaced by **truthfulqa_mc1** and **truthfulqa_mc2**, I guess it is **truthfulqa_mc1**; 

- In fact, we followed the settings from [Open LLM Leaderboard - a Hugging Face Space by HuggingFaceH4](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard), and we reported results for mc2, as mentioned in Section 5.4 of our paper. 

> 3. The **hf-causal-experimental** model should be customized by the author, because the original **lm-evaluation-harness** does not have this type. 

- The hf-causal-experimental model was not custom-made by us; it was provided in the version of the harness available at that time. For instance, this issue also mentions this model class [To evaluate (causal) models across multiple GPUs · Issue #470 · EleutherAI/lm-evaluation-harness (github.com)](https://github.com/EleutherAI/lm-evaluation-harness/issues/470). 


Anyway, we did not make too much modifications to lm-evaluation-harness; we simply hacked it to use local versions of my_modeling_llama and my_configuration_llama when loading models. We believe you will be able to reproduce the results very soon!

**Comment by wutong4012** [comment]
ok, I get it. It would be better if you could provide the branch you were using at the time.

**Comment by dwzhu-pku** [comment]
Thank you so much for your understanding. I'm sure that the version of lm-evalution harness we used is 0.3.0, just the main branch. Sadly, I'm not quite sure about the exact commit. But since this work  was primarily done in July and August, I think you may fetch the main branch during or slightly before that time period, and install it in editable mode. :-) @wutong4012

**Comment by wutong4012** [comment]
Thank you very much for the advice. I have run the results by modifying the main branch of the current version. Maybe due to version issues, some results are slightly different, but most of them are not much different from the reported results.
Thanks again for the open source code.
