### ISSUE TITLE
How to reproduce the ppl behaviours?

### ISSUE THREAD

**Issue by 66RING** [dwzhu-pku/PoSE#9]
the **figures** show that the longer input the **lower** ppl it get.
![image](https://github.com/dwzhu-pku/PoSE/assets/49358576/24e96b9b-cbf6-46dd-b050-2634056ace12)

but the **table** show that the longer input the **larger ppl** it get.

![image](https://github.com/dwzhu-pku/PoSE/assets/49358576/d4d9b1a2-d19b-46b6-9d0e-dae02eb89a35)

**Comment by dwzhu-pku** [comment]
Hi @66RING! Thank you for your thoughtful concern.

The decrease in perplexity (ppl) is actually the expected behavior, as it indicates that the model is effectively utilizing the long context to improve language modeling. You can see this decreasing trend in both Table 1 and Figure 4 of our paper.

As for Table 2, it serves as an extreme case to demonstrate the potential of our method to extend context to a very large scale. The 96k and 128k models were trained using 2k context for 1k steps, similar to previous models. There is still significant room for improvement, such as increasing training steps or training context, to optimize performance. Our main point here is to show that the ppl is still very low, indicating that the 128k model can function normally.

Thank you for your attention to our work. I hope this explanation addresses your concern :-)
